services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passsword
      - MYSQL_ROOT_PASSWORD=passsword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
